#!/bin/bash

phpize && \
./configure && \
make && \
make install && \
echo "extension=swephp.so" > /usr/local/etc/php/conf.d/swephp.ini &&
phpize --clean && \
rm sweph/src/libswe.a && \
rm sweph/src/*.o && \
rmdir include
